influxdb:
  image: quay.io/7insyde/influxdb
  container_name: influxdb
  ports:
      - "8083:8083"
      - "8086:8086"
telegraf:
  image: quay.io/7insyde/telegraf
  container_name: telegraf
  privileged: true
  volumes:
      - /var/run:/var/run
  links:
      - influxdb
grafana:
  image: quay.io/7insyde/grafana
  container_name: grafana
  ports:
      - "3000:3000"
  links:
      - influxdb
